/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Driver extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6128486419125521663L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Driver\",\"namespace\":\"model\",\"fields\":[{\"name\":\"uuid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"drivingLicence\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"driverName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"associatedVehicleUUID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"eventType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String uuid;
  @Deprecated public java.lang.String drivingLicence;
  @Deprecated public java.lang.String driverName;
  @Deprecated public java.lang.String associatedVehicleUUID;
  @Deprecated public java.lang.String eventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Driver() {}

  /**
   * All-args constructor.
   * @param uuid The new value for uuid
   * @param drivingLicence The new value for drivingLicence
   * @param driverName The new value for driverName
   * @param associatedVehicleUUID The new value for associatedVehicleUUID
   * @param eventType The new value for eventType
   */
  public Driver(java.lang.String uuid, java.lang.String drivingLicence, java.lang.String driverName, java.lang.String associatedVehicleUUID, java.lang.String eventType) {
    this.uuid = uuid;
    this.drivingLicence = drivingLicence;
    this.driverName = driverName;
    this.associatedVehicleUUID = associatedVehicleUUID;
    this.eventType = eventType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uuid;
    case 1: return drivingLicence;
    case 2: return driverName;
    case 3: return associatedVehicleUUID;
    case 4: return eventType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uuid = (java.lang.String)value$; break;
    case 1: drivingLicence = (java.lang.String)value$; break;
    case 2: driverName = (java.lang.String)value$; break;
    case 3: associatedVehicleUUID = (java.lang.String)value$; break;
    case 4: eventType = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return The value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'drivingLicence' field.
   * @return The value of the 'drivingLicence' field.
   */
  public java.lang.String getDrivingLicence() {
    return drivingLicence;
  }

  /**
   * Sets the value of the 'drivingLicence' field.
   * @param value the value to set.
   */
  public void setDrivingLicence(java.lang.String value) {
    this.drivingLicence = value;
  }

  /**
   * Gets the value of the 'driverName' field.
   * @return The value of the 'driverName' field.
   */
  public java.lang.String getDriverName() {
    return driverName;
  }

  /**
   * Sets the value of the 'driverName' field.
   * @param value the value to set.
   */
  public void setDriverName(java.lang.String value) {
    this.driverName = value;
  }

  /**
   * Gets the value of the 'associatedVehicleUUID' field.
   * @return The value of the 'associatedVehicleUUID' field.
   */
  public java.lang.String getAssociatedVehicleUUID() {
    return associatedVehicleUUID;
  }

  /**
   * Sets the value of the 'associatedVehicleUUID' field.
   * @param value the value to set.
   */
  public void setAssociatedVehicleUUID(java.lang.String value) {
    this.associatedVehicleUUID = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.String getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.String value) {
    this.eventType = value;
  }

  /**
   * Creates a new Driver RecordBuilder.
   * @return A new Driver RecordBuilder
   */
  public static model.Driver.Builder newBuilder() {
    return new model.Driver.Builder();
  }

  /**
   * Creates a new Driver RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Driver RecordBuilder
   */
  public static model.Driver.Builder newBuilder(model.Driver.Builder other) {
    return new model.Driver.Builder(other);
  }

  /**
   * Creates a new Driver RecordBuilder by copying an existing Driver instance.
   * @param other The existing instance to copy.
   * @return A new Driver RecordBuilder
   */
  public static model.Driver.Builder newBuilder(model.Driver other) {
    return new model.Driver.Builder(other);
  }

  /**
   * RecordBuilder for Driver instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Driver>
    implements org.apache.avro.data.RecordBuilder<Driver> {

    private java.lang.String uuid;
    private java.lang.String drivingLicence;
    private java.lang.String driverName;
    private java.lang.String associatedVehicleUUID;
    private java.lang.String eventType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(model.Driver.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.drivingLicence)) {
        this.drivingLicence = data().deepCopy(fields()[1].schema(), other.drivingLicence);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.driverName)) {
        this.driverName = data().deepCopy(fields()[2].schema(), other.driverName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.associatedVehicleUUID)) {
        this.associatedVehicleUUID = data().deepCopy(fields()[3].schema(), other.associatedVehicleUUID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Driver instance
     * @param other The existing instance to copy.
     */
    private Builder(model.Driver other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.drivingLicence)) {
        this.drivingLicence = data().deepCopy(fields()[1].schema(), other.drivingLicence);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.driverName)) {
        this.driverName = data().deepCopy(fields()[2].schema(), other.driverName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.associatedVehicleUUID)) {
        this.associatedVehicleUUID = data().deepCopy(fields()[3].schema(), other.associatedVehicleUUID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.String getUuid() {
      return uuid;
    }

    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public model.Driver.Builder setUuid(java.lang.String value) {
      validate(fields()[0], value);
      this.uuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public model.Driver.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'drivingLicence' field.
      * @return The value.
      */
    public java.lang.String getDrivingLicence() {
      return drivingLicence;
    }

    /**
      * Sets the value of the 'drivingLicence' field.
      * @param value The value of 'drivingLicence'.
      * @return This builder.
      */
    public model.Driver.Builder setDrivingLicence(java.lang.String value) {
      validate(fields()[1], value);
      this.drivingLicence = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'drivingLicence' field has been set.
      * @return True if the 'drivingLicence' field has been set, false otherwise.
      */
    public boolean hasDrivingLicence() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'drivingLicence' field.
      * @return This builder.
      */
    public model.Driver.Builder clearDrivingLicence() {
      drivingLicence = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverName' field.
      * @return The value.
      */
    public java.lang.String getDriverName() {
      return driverName;
    }

    /**
      * Sets the value of the 'driverName' field.
      * @param value The value of 'driverName'.
      * @return This builder.
      */
    public model.Driver.Builder setDriverName(java.lang.String value) {
      validate(fields()[2], value);
      this.driverName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'driverName' field has been set.
      * @return True if the 'driverName' field has been set, false otherwise.
      */
    public boolean hasDriverName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'driverName' field.
      * @return This builder.
      */
    public model.Driver.Builder clearDriverName() {
      driverName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'associatedVehicleUUID' field.
      * @return The value.
      */
    public java.lang.String getAssociatedVehicleUUID() {
      return associatedVehicleUUID;
    }

    /**
      * Sets the value of the 'associatedVehicleUUID' field.
      * @param value The value of 'associatedVehicleUUID'.
      * @return This builder.
      */
    public model.Driver.Builder setAssociatedVehicleUUID(java.lang.String value) {
      validate(fields()[3], value);
      this.associatedVehicleUUID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'associatedVehicleUUID' field has been set.
      * @return True if the 'associatedVehicleUUID' field has been set, false otherwise.
      */
    public boolean hasAssociatedVehicleUUID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'associatedVehicleUUID' field.
      * @return This builder.
      */
    public model.Driver.Builder clearAssociatedVehicleUUID() {
      associatedVehicleUUID = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.String getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public model.Driver.Builder setEventType(java.lang.String value) {
      validate(fields()[4], value);
      this.eventType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public model.Driver.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Driver build() {
      try {
        Driver record = new Driver();
        record.uuid = fieldSetFlags()[0] ? this.uuid : (java.lang.String) defaultValue(fields()[0]);
        record.drivingLicence = fieldSetFlags()[1] ? this.drivingLicence : (java.lang.String) defaultValue(fields()[1]);
        record.driverName = fieldSetFlags()[2] ? this.driverName : (java.lang.String) defaultValue(fields()[2]);
        record.associatedVehicleUUID = fieldSetFlags()[3] ? this.associatedVehicleUUID : (java.lang.String) defaultValue(fields()[3]);
        record.eventType = fieldSetFlags()[4] ? this.eventType : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
